# Generated by Django 5.0.1 on 2024-03-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLiga', models.CharField(max_length=100)),
                ('federacao', models.CharField(max_length=100)),
                ('serieDivisao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoModalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquipe', models.CharField(max_length=100)),
                ('nomeAbreviado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('modalidadeMasc', models.BooleanField(default=False)),
                ('modalidadeFem', models.BooleanField(default=False)),
                ('logoTime', models.ImageField(upload_to='', verbose_name='app_tdown/logoTime/')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPartida', models.DateField()),
                ('horarioPartida', models.TimeField()),
                ('ruaPartida', models.CharField(max_length=200)),
                ('numeroPartida', models.CharField(max_length=10)),
                ('cidadePartida', models.CharField(max_length=150)),
                ('estadoPartida', models.CharField(max_length=2)),
                ('ligaPartida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.liga')),
                ('modalidadePartida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.modalidade')),
                ('timeCasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_casa', to='app_tdown.time')),
                ('timeVisitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_visitante', to='app_tdown.time')),
            ],
        ),
    ]
