# Generated by Django 5.0.1 on 2024-03-01 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAbrev', models.CharField(max_length=10)),
                ('nomeFederacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='liga',
            name='serieDivisao',
        ),
        migrations.AddField(
            model_name='liga',
            name='nomeAbrevLiga',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DivisoesCampeonatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEDivisao', models.CharField(max_length=10)),
                ('liga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.liga')),
            ],
        ),
        migrations.AlterField(
            model_name='liga',
            name='federacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.federacoes'),
        ),
    ]
