# Generated by Django 5.0.1 on 2024-03-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0002_federacoes_remove_liga_seriedivisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='divisoePartida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.divisoescampeonatos'),
        ),
        migrations.AlterField(
            model_name='divisoescampeonatos',
            name='nomeEDivisao',
            field=models.CharField(max_length=100),
        ),
    ]
