# Generated by Django 5.0.1 on 2024-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0004_partida_nomepartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='logoPartida',
            field=models.ImageField(default='', upload_to='', verbose_name='app_tdown/logoPartida/'),
            preserve_default=False,
        ),
    ]
