# Generated by Django 5.2 on 2025-05-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0005_partida_logopartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclusaoJogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoJogada', models.CharField(max_length=25)),
                ('possuiFalta', models.BooleanField(default=False)),
                ('jogPossuiFumble', models.BooleanField(default=False)),
                ('timeAtaqueRecuperou', models.BooleanField(default=False)),
                ('jogadaComPontuacao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFalta', models.CharField(max_length=250)),
                ('penalidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePontuacao', models.CharField(max_length=25)),
                ('descPontuacao', models.CharField(max_length=2000)),
                ('qtsPonto', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='partida',
            name='logoPartida',
            field=models.ImageField(blank=True, default='', upload_to='app_tdown/covers/logoPartida/'),
        ),
        migrations.AlterField(
            model_name='time',
            name='logoTime',
            field=models.ImageField(upload_to='app_tdown/covers/logoTime/'),
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_quaterback', models.IntegerField()),
                ('n_corredor', models.IntegerField()),
                ('resultado_jogada', models.CharField(max_length=50)),
                ('direcao_corrida', models.CharField(max_length=50)),
                ('qt_jard_percorreu', models.IntegerField()),
                ('gap_corrida', models.CharField(max_length=10)),
                ('def_parou_jogada', models.BooleanField(default=False)),
                ('jogador_parou_jogada', models.IntegerField()),
                ('conclusaoJogada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.conclusaojogada')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaCometida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jogadorFezFalta', models.IntegerField()),
                ('conclusaoJogada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.conclusaojogada')),
                ('timeCometeuFalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.time')),
                ('tipoFalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.falta')),
            ],
        ),
        migrations.CreateModel(
            name='FieldGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_kicker', models.IntegerField()),
                ('resultado_jogada', models.CharField(max_length=50)),
                ('posicao_campo', models.IntegerField()),
                ('def_parou_jogada', models.BooleanField(default=False)),
                ('jogador_parou_jogada', models.IntegerField()),
                ('conclusaoJogada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.conclusaojogada')),
            ],
        ),
        migrations.CreateModel(
            name='Jogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogada', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('descida', models.IntegerField()),
                ('jardaFirst', models.IntegerField()),
                ('posicaoBola', models.IntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.partida')),
                ('timeAtacando', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_atacando', to='app_tdown.time')),
                ('timeDefendendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_defendendo', to='app_tdown.time')),
            ],
        ),
        migrations.AddField(
            model_name='conclusaojogada',
            name='jogada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.jogada'),
        ),
        migrations.CreateModel(
            name='Passe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_quaterback', models.IntegerField()),
                ('n_recebedor', models.IntegerField()),
                ('resultado_jogada', models.CharField(max_length=50)),
                ('direcao_passe', models.CharField(max_length=50)),
                ('qt_jard_percorreu', models.IntegerField()),
                ('profundidade_passe', models.CharField(max_length=50)),
                ('def_parou_jogada', models.BooleanField(default=False)),
                ('jogador_parou_jogada', models.IntegerField()),
                ('conclusaoJogada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.conclusaojogada')),
            ],
        ),
        migrations.AddField(
            model_name='conclusaojogada',
            name='tipoPontuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tdown.pontuacao'),
        ),
        migrations.CreateModel(
            name='Punt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_kicker', models.IntegerField()),
                ('resultado_jogada', models.CharField(max_length=50)),
                ('posicao_campo', models.IntegerField()),
                ('qt_jard_punt', models.IntegerField()),
                ('teve_retorno', models.BooleanField(default=False)),
                ('n_jogadorRetorno', models.IntegerField()),
                ('qt_jard_retorno', models.IntegerField()),
                ('def_parou_jogada', models.BooleanField(default=False)),
                ('jogador_parou_jogada', models.IntegerField()),
                ('conclusaoJogada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tdown.conclusaojogada')),
            ],
        ),
    ]
