# Generated by Django 5.2 on 2025-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0006_conclusaojogada_falta_pontuacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='descFalta',
            field=models.CharField(default='Sem descrição', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='falta',
            name='penalidade',
            field=models.CharField(max_length=500),
        ),
    ]
