# Generated by Django 5.2 on 2025-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdown', '0007_falta_descfalta_alter_falta_penalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='jogador_parou_jogada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldgoal',
            name='jogador_parou_jogada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passe',
            name='jogador_parou_jogada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punt',
            name='jogador_parou_jogada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punt',
            name='n_jogadorRetorno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punt',
            name='qt_jard_retorno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
